// GENERATED by scripts/extract-arcade-kit.py -- do not edit by hand.
// Source of truth: scripts/arcade-kit.manifest.json + the concept art.

import img_wordmark from "./masthead/wordmark.png";
import img_plate_menu_cyan from "./plate/menu-cyan.png";
import img_plate_menu_gold from "./plate/menu-gold.png";
import img_plate_menu_purple from "./plate/menu-purple.png";
import img_plate_menu_green from "./plate/menu-green.png";
import img_plate_menu_red from "./plate/menu-red.png";
import img_panel_info_cyan from "./frame/panel-info-cyan.png";
import img_panel_notice from "./frame/panel-notice.png";
import img_panel_browser from "./frame/panel-browser.png";
import img_row_selected from "./frame/row-selected.png";
import img_badge_signed_in from "./frame/badge-signed-in.png";
import img_panel_profile from "./frame/panel-profile.png";
import img_panel_recovery from "./frame/panel-recovery.png";
import img_panel_activity from "./frame/panel-activity.png";
import img_strip_tip from "./frame/strip-tip.png";
import img_meter_xp from "./meter/meter-xp.png";
import img_inset_stat from "./frame/inset-stat.png";
import img_icon_bolt from "./icon/bolt.png";
import img_icon_plus_gold from "./icon/plus-gold.png";
import img_icon_grid_purple from "./icon/grid-purple.png";
import img_icon_grid_green from "./icon/grid-green.png";
import img_icon_recycle_red from "./icon/recycle-red.png";
import img_icon_lock_circle from "./icon/lock-circle.png";
import img_icon_star from "./icon/star.png";
import img_icon_chevron_left from "./icon/chevron-left.png";
import img_icon_chevron_right from "./icon/chevron-right.png";
import img_icon_chat from "./icon/chat.png";
import img_tab_arcade_league from "./frame/tab-arcade-league.png";
import img_card_competitor_gold from "./card/competitor-gold.png";
import img_card_competitor_purple from "./card/competitor-purple.png";
import img_card_competitor_pink from "./card/competitor-pink.png";
import img_card_competitor_green from "./card/competitor-green.png";
import img_panel_round from "./frame/panel-round.png";
import img_panel_turn_lcd from "./frame/panel-turn-lcd.png";
import img_lcd_screen from "./lcd/lcd-screen.png";
import img_meter_segment from "./meter/meter-segment.png";
import img_panel_log from "./frame/panel-log.png";
import img_panel_howto from "./frame/panel-howto.png";
import img_sprite_mascot from "./sprite/mascot.png";
import img_bubble_speech from "./frame/bubble-speech.png";
import img_board_frame from "./board/board-frame.png";
import img_rack_band from "./board/rack-band.png";
import img_tile_face from "./tile/tile-face.png";
import img_pip_diamond from "./tile/pip-diamond.png";
import img_pip_circle from "./tile/pip-circle.png";
import img_pip_triangle from "./tile/pip-triangle.png";
import img_pip_square from "./tile/pip-square.png";
import img_plate_action_cyan from "./plate/action-cyan.png";
import img_plate_action_purple from "./plate/action-purple.png";
import img_plate_action_dim from "./plate/action-dim.png";
import img_plate_action_orange from "./plate/action-orange.png";
import img_icon_draw_stack from "./icon/draw-stack.png";
import img_icon_pass_hand from "./icon/pass-hand.png";
import img_icon_sort_tiles from "./icon/sort-tiles.png";
import img_icon_commit_arrow from "./icon/commit-arrow.png";
import img_button_gear from "./icon/button-gear.png";
import img_button_speaker from "./icon/button-speaker.png";
import img_footer_strip_phone from "./frame/footer-strip-phone.png";
import img_button_square_menu from "./icon/button-square-menu.png";

export interface ArcadeAsset {
  url: string;
  width: number;
  height: number;
  /** 9-slice border-image insets in source pixels, if framed. */
  slice?: { top: number; right: number; bottom: number; left: number };
}

export const arcadeAssets = {
  "wordmark": { url: img_wordmark, width: 672, height: 224 },
  "plate-menu-cyan": { url: img_plate_menu_cyan, width: 344, height: 112, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "plate-menu-gold": { url: img_plate_menu_gold, width: 348, height: 126, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "plate-menu-purple": { url: img_plate_menu_purple, width: 348, height: 106, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "plate-menu-green": { url: img_plate_menu_green, width: 348, height: 118, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "plate-menu-red": { url: img_plate_menu_red, width: 348, height: 118, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "panel-info-cyan": { url: img_panel_info_cyan, width: 292, height: 100, slice: { top: 14, right: 14, bottom: 14, left: 14 } },
  "panel-notice": { url: img_panel_notice, width: 480, height: 154, slice: { top: 16, right: 14, bottom: 14, left: 14 } },
  "panel-browser": { url: img_panel_browser, width: 762, height: 552, slice: { top: 18, right: 18, bottom: 18, left: 18 } },
  "row-selected": { url: img_row_selected, width: 686, height: 44, slice: { top: 12, right: 16, bottom: 12, left: 16 } },
  "badge-signed-in": { url: img_badge_signed_in, width: 380, height: 100, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "panel-profile": { url: img_panel_profile, width: 362, height: 266, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "panel-recovery": { url: img_panel_recovery, width: 362, height: 136, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "panel-activity": { url: img_panel_activity, width: 368, height: 200, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "strip-tip": { url: img_strip_tip, width: 1046, height: 62, slice: { top: 14, right: 14, bottom: 14, left: 14 } },
  "meter-xp": { url: img_meter_xp, width: 172, height: 18, slice: { top: 5, right: 6, bottom: 5, left: 6 } },
  "inset-stat": { url: img_inset_stat, width: 168, height: 72, slice: { top: 10, right: 10, bottom: 10, left: 10 } },
  "icon-bolt": { url: img_icon_bolt, width: 66, height: 80 },
  "icon-plus-gold": { url: img_icon_plus_gold, width: 84, height: 80 },
  "icon-grid-purple": { url: img_icon_grid_purple, width: 74, height: 62 },
  "icon-grid-green": { url: img_icon_grid_green, width: 72, height: 66 },
  "icon-recycle-red": { url: img_icon_recycle_red, width: 82, height: 82 },
  "icon-lock-circle": { url: img_icon_lock_circle, width: 84, height: 84 },
  "icon-star": { url: img_icon_star, width: 28, height: 28 },
  "icon-chevron-left": { url: img_icon_chevron_left, width: 46, height: 32 },
  "icon-chevron-right": { url: img_icon_chevron_right, width: 46, height: 32 },
  "icon-chat": { url: img_icon_chat, width: 62, height: 58 },
  "tab-arcade-league": { url: img_tab_arcade_league, width: 256, height: 102, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "card-competitor-gold": { url: img_card_competitor_gold, width: 254, height: 212, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "card-competitor-purple": { url: img_card_competitor_purple, width: 248, height: 168, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "card-competitor-pink": { url: img_card_competitor_pink, width: 236, height: 160, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "card-competitor-green": { url: img_card_competitor_green, width: 236, height: 170, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "panel-round": { url: img_panel_round, width: 254, height: 118, slice: { top: 14, right: 14, bottom: 14, left: 14 } },
  "panel-turn-lcd": { url: img_panel_turn_lcd, width: 258, height: 216, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "lcd-screen": { url: img_lcd_screen, width: 218, height: 74, slice: { top: 10, right: 10, bottom: 10, left: 10 } },
  "meter-segment": { url: img_meter_segment, width: 200, height: 24, slice: { top: 6, right: 8, bottom: 6, left: 8 } },
  "panel-log": { url: img_panel_log, width: 260, height: 222, slice: { top: 14, right: 14, bottom: 14, left: 14 } },
  "panel-howto": { url: img_panel_howto, width: 258, height: 296, slice: { top: 14, right: 14, bottom: 14, left: 14 } },
  "sprite-mascot": { url: img_sprite_mascot, width: 68, height: 98 },
  "bubble-speech": { url: img_bubble_speech, width: 176, height: 78, slice: { top: 12, right: 14, bottom: 12, left: 20 } },
  "board-frame": { url: img_board_frame, width: 936, height: 490 },
  "rack-band": { url: img_rack_band, width: 928, height: 184, slice: { top: 36, right: 22, bottom: 8, left: 22 } },
  "tile-face": { url: img_tile_face, width: 78, height: 112, slice: { top: 14, right: 16, bottom: 22, left: 14 } },
  "pip-diamond": { url: img_pip_diamond, width: 26, height: 24 },
  "pip-circle": { url: img_pip_circle, width: 26, height: 24 },
  "pip-triangle": { url: img_pip_triangle, width: 28, height: 26 },
  "pip-square": { url: img_pip_square, width: 24, height: 22 },
  "plate-action-cyan": { url: img_plate_action_cyan, width: 258, height: 118, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "plate-action-purple": { url: img_plate_action_purple, width: 246, height: 118, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "plate-action-dim": { url: img_plate_action_dim, width: 244, height: 118, slice: { top: 16, right: 16, bottom: 16, left: 16 } },
  "plate-action-orange": { url: img_plate_action_orange, width: 360, height: 122, slice: { top: 16, right: 20, bottom: 16, left: 20 } },
  "icon-draw-stack": { url: img_icon_draw_stack, width: 62, height: 56 },
  "icon-pass-hand": { url: img_icon_pass_hand, width: 52, height: 58 },
  "icon-sort-tiles": { url: img_icon_sort_tiles, width: 74, height: 44 },
  "icon-commit-arrow": { url: img_icon_commit_arrow, width: 58, height: 44 },
  "button-gear": { url: img_button_gear, width: 70, height: 68 },
  "button-speaker": { url: img_button_speaker, width: 72, height: 68 },
  "footer-strip-phone": { url: img_footer_strip_phone, width: 706, height: 56, slice: { top: 14, right: 14, bottom: 14, left: 14 } },
  "button-square-menu": { url: img_button_square_menu, width: 82, height: 82 },
} as const satisfies Record<string, ArcadeAsset>;

export type ArcadeAssetName = keyof typeof arcadeAssets;
